openapi: 3.0.0
info:
  title: 채용 공고 및 회원 관리 API 문서
  description: 회원 관리, 채용 공고 관리, 지원 관리, 북마크 관리 API 명세서
  version: 1.0.0
servers:
  - url: http://113.198.66.75:10217
    description: Swagger hosted API server
paths:
  /auth/register:
    post:
      summary: 회원 가입
      description: 이메일 형식 검증, 비밀번호 암호화, 중복 회원 검사 후 사용자 정보를 저장합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: 회원 가입 성공
        '400':
          description: 잘못된 요청

  /auth/login:
    post:
      summary: 로그인
      description: 사용자 인증 후 JWT 토큰을 발급합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 로그인 성공, 토큰 반환
        '401':
          description: 인증 실패

  /auth/refresh:
    post:
      summary: 토큰 갱신
      description: Refresh 토큰을 검증하고 새로운 Access 토큰을 발급합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: 토큰 갱신 성공
        '401':
          description: 토큰 갱신 실패

  /jobs:
    get:
      summary: 채용 공고 목록 조회
      description: 페이징 처리된 채용 공고 목록을 반환합니다.
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
          description: 페이지 번호
        - name: size
          in: query
          required: false
          schema:
            type: integer
          description: 페이지 크기 (기본값: 20)
      responses:
        '200':
          description: 공고 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        '500':
          description: 서버 오류

  /jobs/{id}:
    get:
      summary: 공고 상세 조회
      description: 공고 ID를 기반으로 상세 정보를 반환하며, 관련 공고 3개를 추천합니다.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 공고 ID
      responses:
        '200':
          description: 공고 상세 정보 및 추천 공고 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDetails'
        '404':
          description: 공고를 찾을 수 없음

  /applications:
    get:
      summary: 지원 내역 조회
      description: 사용자별 지원 목록을 조회합니다.
      responses:
        '200':
          description: 지원 내역 반환
        '401':
          description: 인증 실패
    post:
      summary: 지원 등록
      description: 사용자가 공고에 지원합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
      responses:
        '201':
          description: 지원 등록 성공
        '400':
          description: 잘못된 요청

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: 사용자 이메일
        password:
          type: string
          format: password
          description: 사용자 비밀번호
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: 사용자 이메일
        password:
          type: string
          format: password
          description: 사용자 비밀번호
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
          description: Refresh 토큰
    Job:
      type: object
      properties:
        id:
          type: integer
          description: 공고 ID
        title:
          type: string
          description: 공고 제목
        company:
          type: string
          description: 회사 이름
        location:
          type: string
          description: 근무지
    JobDetails:
      type: object
      properties:
        job:
          $ref: '#/components/schemas/Job'
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/Job'
    ApplicationRequest:
      type: object
      properties:
        jobId:
          type: integer
          description: 지원하려는 공고 ID
